#! /bin/sh

# .bashrc
# alias 1centerprise="docker run --rm -e DISPLAY=$DISPLAY -v $HOME/.Xauthority:/home/developer/.Xauthority -v $HOME:/home/developer -v /win-d:/mnt/ --net=host --pid=host --ipc=host z-ank/1c &"
docker run -ti --rm -e DISPLAY=$DISPLAY -v $HOME/.Xauthority:/home/developer/.Xauthority -v $HOME:/home/developer --net=host --pid=host --ipc=host z-ank/1c
